services:
  postgresql:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=${PASSWORD}
    container_name: postgresql
    ports:
      - 5432:5432
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${PASSWORD}
    container_name: mssql
    ports:
      - 1433:1433
  mysql:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
    container_name: mysql
    ports:
      - 3306:3306
  # sqlpipe:
  #   build:
  #     context: ./
  #     dockerfile: oracle.dockerfile
  #   container_name: sqlpipe
  #   ports:
  #     - 9000:9000